console.log("hii");
console.log("hii");
// if we use try and catch then it will not give error
console.log(a); // here it will give error because it will not have their value which we can't assign  it 
console.log("hii");
console.log("hii");